docu: "https://jekyllrb.com/docs/variables/"
theXme: jekyll-theme-cayman

# Name of the site (displayed in the header)
title: mon-super-site

# Short description (displayed in the header)
description: "pour tester les pages de github"

Xshow_downloads: "true" or "false" to indicate whether to provide a download URL

Xgoogle_analytics: "Google Analytics tracking ID"

Xgithub:
  zip_url: "http://example.com/download.zip"
  another_url: "another value"
