theXme: jekyll-theme-cayman

# Name of the site (displayed in the header)
name: mon-super-site

# Short description (displayed in the header)
description: pour tester les pages de github

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/12160504

# https://github.com/barryclark/jekyll-now/blob/master/_config.yml
