# "https://jekyllrb.com/docs/variables/"

# theme: jekyll-theme-cayman

# Name of the site (displayed in the header)
title: Deep Perl

# Short description (displayed in the header)
description: 25 ans avec Perl 5 - 25 years with Perl 5

# show_downloads: "true" or "false" to indicate whether to provide a download URL

# google_analytics: "Google Analytics tracking ID"

# github:
#  zip_url: "http://example.com/download.zip"
#  another_url: "another value"
